export default function AboutPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-8 md:py-12">
      <header className="mb-8">
        <h1 className="text-4xl md:text-5xl font-extrabold font-headline text-foreground leading-tight mb-4">
          About Daily Chronicles
        </h1>
      </header>
      <div className="prose-styles max-w-none text-foreground/90">
        <p>
          Welcome to Daily Chronicles, your go-to source for insightful articles and stories generated by cutting-edge artificial intelligence. Our mission is to explore the frontiers of technology, business, finance, and culture, delivering fresh perspectives and in-depth analysis every single day.
        </p>
        <h2>Our Vision</h2>
        <p>
          In a world overflowing with information, we believe in the power of AI to sift through the noise and deliver content that is not only relevant and accurate but also engaging and thought-provoking. We aim to be a premier destination for readers who are curious about the world and excited about the future.
        </p>
        <p>
          Our content spans a wide range of categories, including:
        </p>
        <ul>
          <li><strong>IT and Technology:</strong> Stay updated on the latest trends in software development, cybersecurity, and quantum computing.</li>
          <li><strong>Business and Finance:</strong> Gain insights into market dynamics, investment strategies, and corporate leadership.</li>
          <li><strong>Travel and Lifestyle:</strong> Discover new destinations and get tips for your next adventure.</li>
          <li><strong>And much more...</strong> Our AI is constantly learning and expanding its knowledge base to cover new and exciting topics.</li>
        </ul>
        <h2>Our Technology</h2>
        <p>
          Daily Chronicles is powered by advanced generative AI models. These models are trained on vast datasets to produce high-quality, coherent, and original content. While our articles are AI-generated, they are curated and reviewed to ensure they meet our high standards for quality and accuracy.
        </p>
        <h2>Join Our Community</h2>
        <p>
          We are more than just a blog; we are a community of forward-thinkers, innovators, and lifelong learners. We invite you to read, comment, and share our articles. Your engagement helps us grow and improve.
        </p>
        <p>
          Thank you for visiting Daily Chronicles. We're excited to have you with us on this journey of discovery.
        </p>
      </div>
    </div>
  );
}
