
import { getPosts } from '@/lib/posts';
import { TodaysPosts } from '@/components/todays-posts';
import SearchPosts from '@/components/search-posts';

export default async function HomePage({ searchParams }: { searchParams?: { query?: string } }) {
  const query = searchParams?.query || '';
  const allPosts = await getPosts({ query });

  return (
    <>
      <div className="flex flex-col md:flex-row md:items-center md:justify-between mb-8 gap-4">
        <div>
          <h1 className="text-4xl font-bold font-headline mb-2 text-foreground">
            Latest Chronicles
          </h1>
          <p className="text-muted-foreground">The latest posts, generated by AI.</p>
        </div>
        <SearchPosts />
      </div>

      {query ? (
        <h2 className="text-2xl font-bold font-headline mb-8 text-foreground">
          Search Results for "{query}"
        </h2>
      ) : null}

      <TodaysPosts allPosts={allPosts} isSearchResults={!!query} />
    </>
  );
}
