export default function TermsOfServicePage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-8 md:py-12">
      <header className="mb-8">
        <h1 className="text-4xl md:text-5xl font-extrabold font-headline text-foreground leading-tight mb-4">
          Terms of Service
        </h1>
        <p className="text-muted-foreground">Last Updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
      </header>
      <div className="prose-styles max-w-none text-foreground/90">
        <h2>1. Agreement to Terms</h2>
        <p>
          By using our website, Daily Chronicles (the "Site"), you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use the Site. We may modify these Terms at any time, and such modification shall be effective immediately upon posting of the modified Terms.
        </p>

        <h2>2. Use of the Site</h2>
        <p>
          You agree to use the Site only for lawful purposes. You are prohibited from any use of the Site that would constitute an illegal offense, give rise to liability, or otherwise violate any applicable local, state, national, or international law or regulation.
        </p>
        <p>
          All content on this site is generated by an artificial intelligence. While we strive for accuracy, we make no guarantees about the reliability, completeness, or timeliness of the content. The information provided is for general informational purposes only and does not constitute professional advice.
        </p>

        <h2>3. Intellectual Property</h2>
        <p>
          The content, organization, graphics, design, and other matters related to the Site are protected under applicable copyrights and other proprietary laws, including but not limited to intellectual property laws. The copying, reproduction, use, modification, or publication by you of any such matters or any part of the Site is strictly prohibited, without our express prior written permission.
        </p>

        <h2>4. User-Generated Content</h2>
        <p>
          If you post, upload, or make available any material, you grant us a non-exclusive, royalty-free, perpetual, and worldwide license to use, reproduce, modify, and distribute such content. You are responsible for the content you provide and must ensure you have the rights to do so.
        </p>

        <h2>5. Limitation of Liability</h2>
        <p>
          In no event shall Daily Chronicles or its affiliates be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on the Site, even if we have been notified orally or in writing of the possibility of such damage.
        </p>

        <h2>6. Governing Law</h2>
        <p>
          These terms and conditions are governed by and construed in accordance with the laws of our operating jurisdiction, and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.
        </p>

        <h2>7. Contact Us</h2>
        <p>
          If you have any questions about these Terms, please contact us via our <a href="/contact">contact page</a>.
        </p>
      </div>
    </div>
  );
}
